CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
    character_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(16) NOT NULL UNIQUE CHECK (name ~ '^[A-Za-z]{3,}$'),
    hair_color CHAR(7) NOT NULL CHECK (hair_color ~ '^#[0-9A-Fa-f]{6}$'),
    hp_max INTEGER NOT NULL CHECK (hp_max >= 0),
    hp INTEGER NOT NULL CHECK (hp >= 0) CHECK (hp_max >= hp),
    blood_type VARCHAR(5) CHECK (blood_type IN ('A', 'B', 'O', 'AB')),
    height_cm DECIMAL(4, 1) NOT NULL CHECK (height_cm BETWEEN 50 AND 250),
    created_on DATE NOT NULL CHECK (created_on >= '2025-12-01') CHECK (created_on <= CURRENT_DATE),
    deleted_on DATE CHECK (deleted_on >= created_on)
);

-- 
mobile_phone CHAR(13) NOT NULL CHECK (mobile_phone ~ '^(90|80|70)-[0-9]{4}-[0-9]{4}$') zip_code CHAR(8) NOT NULL CHECK (zip_code ~ '^[0-9]{3}-[0-9]{4}$')